### ISSUE TITLE
Printing Number Pattern

### ISSUE THREAD

**Issue by prathamesh-borse** [pyGuru123/Hacktoberfest-2021#4]
Hello, @pyGuru123 I would like to contribute to this repository by adding the source code to print the number pattern for a given value of 'n'. Could you please assign this issue to me?
Thank you

**Comment by Durg-PG** [comment]
I would like to contribute to this repository by adding the source code to print the number pattern for a given value of 'n'. Could you please assign this issue to me?
Thank you

**Comment by pyGuru123** [comment]
Go for it
